### ISSUE TITLE
.NET Standard v2.1 not working (Old Issue title: .NET Core 3.1 not working)

### ISSUE THREAD

**Issue by yuki-mizutani-azp** [xpouyat/MK.IO#17]
I am using Azure Media Services with a .NET Core 3.1 solution.
I would really like to use this library for migration, but it is not available due to a dependency error.
Can you please make it available?

Thank you.

**Comment by xpouyat** [comment]
Hello,
Sure, I added .Net Core 3.1 compatibility. Please update to version 1.0.10 and let me know if this works.
https://www.nuget.org/packages/MK.IO/

**Comment by yuki-mizutani-azp** [comment]
I will try it!!
Thanks for the quick response.

**Comment by yuki-mizutani-azp** [comment]
Hello

Sorry, I was using Azure Media Services from a .NET Standard v2.1 project (the same solution had a .NET Core 3.1 project).
I am getting a warning that it is not compatible.
Can you please support .NET Standard v2.1?

Also, I get the following CS1705 compile error when I try to get it from nuget and use it.
How should I deal with this?
Will .NET Standard v2.1 solve this problem?

CS1705
Assembly 'MK.IO' (ID 'MK.IO, Version=1.0.10.0, Culture=neutral, PublicKeyToken=null') uses 
'System.Runtime' (ID 'System. Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') 
which has a higher version than referenced assembly
'System.Runtime' (ID 'System. Runtime  Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

**Comment by xpouyat** [comment]
Hi,
I added support for .NET Standard and re-released the SDK.
See https://www.nuget.org/packages/MK.IO/1.0.11#supportedframeworks-body-tab

I don't know if this will solve CS1705. Please try the new version.

**Comment by yuki-mizutani-azp** [comment]
Hello.
Thanks as always for your quick response.

I tried from nuget and CS1705 was still the same.
I cloned the solution, linked it to my project and started it and it worked.

Here is my guess.
I am a little concerned that you are building with `dotnet-version: 7.x` in github workflows.
Runtime seems to have changed before and after .NET 7.
CS1705 occurred when I linked directly to netcoreapp3.1 MK.IO DLL (v1.0.10.0) and netstandard2.0 MK.IO DLL (v1.0.11.0) from nuget's download folder.
At the time of build, all MK.IO.DLLs seem to be using System.Runtime version 7.0.0.0.

Reference
https://learn.microsoft.com/en-US/dotnet/standard/net-standard?tabs=net-standard-2-1#tabpanel_1_net-standard-2-1
https://stackoverflow.com/questions/75779845/dll-from-a-net-7-project-in-net-3-1-project

The best I can hope for is to be able to get it from nuget and use it as is in my solution.
I will continue to investigate and would appreciate it if you could contact me as soon as you find out something there as well.

**Comment by xpouyat** [comment]
Ok, I was able to reproduce the problem. I will investigate.

**Comment by xpouyat** [comment]
I think I have fixed the issue for .Net Core, but still have a problem for .Net framework 4.8

**Comment by xpouyat** [comment]
I finally found the issue! It took me time.. It was a problem with my GitHub action script which was putting all the SDK DLL from various .Net versions in the same folder. Then the nuget package was incorrect.
Please try version 1.0.14 on Nuget. It should work now.

**Comment by yuki-mizutani-azp** [comment]
Hello.

I just tried it and it works!
Thank you for solving the problem from my poor guess.
