### ISSUE TITLE
JsonProperty for OdataType in ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader

### ISSUE THREAD

**Issue by acvila-de-munte** [xpouyat/MK.IO#38]
Hello!

Is it necessary to put **[JsonProperty("@odata.type")]** attribute on OdataType property in ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader class?

I mean [here](https://github.com/xpouyat/MK.IO/blob/master/MK.IO/ContentKeyPolicy/Models/ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader.cs)

Thank you

**Comment by acvila-de-munte** [comment]
And I believe that property should override the base class OdataType.

**Comment by xpouyat** [comment]
Hello,
Yes, I think you are right. I fixed it in the dev branch. https://github.com/xpouyat/MK.IO/commit/c3a547a73caf3be02bd9f6fe0bda0d4c71742c45
Did you hit an issue because of that ?

**Comment by acvila-de-munte** [comment]
I did, I wasn't able to create content key policy and appears that json didn't have proper contentKeyLocation despite I set it in model.

![image](https://github.com/xpouyat/MK.IO/assets/11018110/50a2613e-1371-4298-bf6b-20fbd1c64a36)
Thank you!

**Comment by xpouyat** [comment]
Please try v1.2.0
https://www.nuget.org/packages/MK.IO/1.2.0

**Comment by xpouyat** [comment]
@acvila-de-munte Please let me know if that works better.

**Comment by acvila-de-munte** [comment]
@xpouyat hello!
I've just tried and it works as expected. No errors during creation and the policy has **Created** status
![image](https://github.com/xpouyat/MK.IO/assets/11018110/d1901614-e955-44c2-ba43-c7b2237cb68d)

Also I've spotted that there are lots of improvements in the new package version.
Thank you for resolving the issue and the additional improvements!
