### ISSUE TITLE
Support AlternateId for Assets

### ISSUE THREAD

**Issue by christianduic** [xpouyat/MK.IO#40]
I'm currently testing MediaKind as a replacement for AMS. 

For backwards compatibility reasons it would be much appreciated to have support in the` Assets.CreateOrUpdateAsync` to provide an `AltenateId `so it can be set in the `AssetProperties`.

Do you think this is a reasonable improvement to the library?

**Comment by xpouyat** [comment]
Oh you are right. I can add this parameter to the CreateOrUpdateAsync method.
I can also add a method which takes the asset properties as parameter for the creation.

Something like we have for content key policy creation
ContentKeyPolicySchema CreateAsync(string contentKeyPolicyName, ContentKeyPolicyProperties properties);

**Comment by xpouyat** [comment]
Possible in v1.2.1 https://www.nuget.org/packages/MK.IO/1.2.1

**Comment by christianduic** [comment]
Thank you! That solves our issue. 

A new `CreateAsync` taking the properties could be more compact, but this change is good enought in our case 💪🏻

**Comment by xpouyat** [comment]
Great. FYI, I also tested .AssetId but it seems ignored at Creation. I will report it to MediaKind.
