### ISSUE TITLE
Error from MKIO API "Streaming Endpoint load failed. 'cdnProvider' field only valid if CDN is enabled" in new 1.2.0 package.

### ISSUE THREAD

**Issue by acvila-de-munte** [xpouyat/MK.IO#41]
If you try to create the streaming endpoint with the new package 1.2.0 with the model provided below you can get an error from mediakind api

> Streaming Endpoint load failed. 'cdnProvider' field only valid if CDN is enabled.

I believe it is because in the `StreamingEndpointProperties` class has `CdnProvider` property of `StreamingEndpointCdnProvider` type (enum) and it isn't nullable and by default has `StandardAkamai` value

![image](https://github.com/xpouyat/MK.IO/assets/11018110/1422ed6d-a559-4dc7-b85d-813879151d23)

code example
```
var properties = new StreamingEndpointProperties
{
	Description = "my description",
	ScaleUnits = 0,
	Sku = new StreamingEndpointsCurrentSku
	{
		Name = "Standard",
		Capacity = 600
	}
};
```
![image](https://github.com/xpouyat/MK.IO/assets/11018110/29aa1f4f-6ee2-492e-a8a3-459f71468db3)
![image](https://github.com/xpouyat/MK.IO/assets/11018110/baf885b2-abb4-40f9-aa41-80880275740a)
Thank you!

**Comment by xpouyat** [comment]
Thanks. I imported some new classes and looks like there is a side effect. I will fix it.

**Comment by xpouyat** [comment]
Should be fixed in v1.2.1 https://www.nuget.org/packages/MK.IO/1.2.1

**Comment by acvila-de-munte** [comment]
Great 😊 thank you! I’ll try it on Monday then

**Comment by xpouyat** [comment]
Any update ?

**Comment by acvila-de-munte** [comment]
No update, didn't have time to check. I'll try to do this next week on Monday

**Comment by acvila-de-munte** [comment]
Hello @xpouyat 
I've just tried and looks fine.
Thank you!
