### ISSUE TITLE
Create locator for asset fails when EndTime is set - Error from MKIO API "Streaming Locator load failed."

### ISSUE THREAD

**Issue by jbaldwinson** [xpouyat/MK.IO#43]
Trying to create a locator for an asset with a endtime set 2 hours ahead (Utc.Now + 2 Hours) and the Api fails with:
![image](https://github.com/xpouyat/MK.IO/assets/61689378/33417a18-167c-476d-bf9d-cc790c0857a3)

Code used to create locator is as follows:
` var newLocatorProps = new MK.IO.Models.StreamingLocatorProperties
 {
     AssetName = assetname,
     StartTime = DateTime.UtcNow,
     EndTime = DateTime.UtcNow.AddHours(2),
     StreamingPolicyName = "Predefined_ClearStreamingOnly"
 };
 var newLocator = await client.StreamingLocators.CreateAsync(Guid.NewGuid().ToString(), newLocatorProps);` 

If endtime is removed then to operation completes successfully. 

Version used 1.2.1 with Asp.Net 8 website. Based in UK so dd/mm/yyyy date format, shouldn't matter but you never know!

**Comment by xpouyat** [comment]
Good catch! I fixed it https://github.com/xpouyat/MK.IO/commit/9ced27c4ded9e30cf2ba4733117c915d0502b430
A new release (1.2.2) should be available in a few minutes on Nugget.

**Comment by jbaldwinson** [comment]
Awesome. Thanks for the quick fix. Can confirm it works as expected with 1.2.2.
