### ISSUE TITLE
Configuring ContentKeyPolicy for FairPlay DRM fails with error "Unsupported @odata.type #Microsoft.Media.ContentKeyPolicyConfigurationFairPlay"

### ISSUE THREAD

**Issue by ben-voytko-talogy** [xpouyat/MK.IO#46]
Attempting to create our content key policy with FairPlay DRM results in a request error when attempting to create.

```
Bad Request : Failed to process payload. Unsupported @odata.type #Microsoft.Media.ContentKeyPolicyConfigurationFairPlay

Status: 400
Response: 
{
  "error": {
    "code": "1000.2000.2000.1040",
    "detail": "Failed to process payload. Unsupported @odata.type #Microsoft.Media.ContentKeyPolicyConfigurationFairPlay"
  },
  "ref": "90db1892-0a84-45b6-be88-6828f2dad49b",
  "status": 400
}
```

with StackTrace:

 ```
  at MK.IO.MKIOClient.AnalyzeResponseAndThrowIfNeeded(HttpResponseMessage amsRequestResult, String responseContent)
   at MK.IO.MKIOClient.<CreateObjectInternalAsync>d__75.MoveNext()
   at MK.IO.MKIOClient.<CreateObjectPutAsync>d__72.MoveNext()
   at MK.IO.ContentKeyPoliciesOperations.<CreateAsync>d__14.MoveNext()
```

It appears that the odata.type for FairPlay may need to be changed to "#Microsoft.Media.ContentKeyPolicyFairPlayConfiguration" (as seen when viewing an existing configured content key policy on MK.io portal) instead of "#Microsoft.Media.ContentKeyPolicyConfigurationFairPlay"

**Comment by xpouyat** [comment]
Hello, thanks for the report.
I fixed the code https://github.com/xpouyat/MK.IO/commit/cfc678949ea7fbb18b8e9c798af94345ecd46015 and will generate a new version of the SDK

**Comment by ben-voytko-talogy** [comment]
Thanks Xavier!

**Comment by ben-voytko-talogy** [comment]
Confirmed the above error is no longer present when trying to create content key policy for FairPlay.

**Comment by ben-voytko-talogy** [comment]
Confirmed I was able to create content key policy with Fairplay without error after the update.
