### ISSUE TITLE
Job Validation failed

### ISSUE THREAD

**Issue by stummer** [xpouyat/MK.IO#50]
We create a JobInputHttp with given start and end times based on Timespans:
```
var jobInput = new MK.IO.Models.JobInputHttp(null, new List<string> { sourceURL });
if (timeStart != null)
    jobInput.Start = new MK.IO.Models.AbsoluteClipTime(timeStart.Value);
if (timeEnd != null)
    jobInput.End = new MK.IO.Models.AbsoluteClipTime(timeEnd.Value);
```

But when we're creating the job, we get the following error:
Bad Request : Job Validation failed. Unsupported @odata.type #Microsoft.Media.AbsoluteClipTime

And looking into "MK.IO.Models.AbsoluteClipTime" I can see the following definition:
```
[JsonProperty("@odata.type")]
internal override string OdataType => "#Microsoft.Media.AbsoluteClipTime";
```

**Comment by ASchmidt1** [comment]
It's included in the MK/IO API documentation:
https://docs.io.mediakind.com/reference/put_apiamsproject_nametransformstransform_namejobsjob_name
and **reproducible** with _their_ native API.

So the job validation error might actually be a bug in MK/IO API implementation itself, not with this library.

**Comment by ASchmidt1** [comment]
MK/IO support confirmed that...
"AboluteClipTime and is not currently supported. Our encoder code supports this but MK.IO does not yet."

So their API doc/specs unfortunately are not representative with what's _actually_ implemented.  :-(

**Comment by xpouyat** [comment]
Yes, I wonder if I should remove the feature from the SDK... Feature is documented in MK.IO API but not enabled....

**Comment by ASchmidt1** [comment]
_>> I wonder if I should remove the feature from the SDK. <<_

They have indicated that the API Documentation is correct, just that the function hadn't been implemented yet, and that the overlooked support will be added.
