### ISSUE TITLE
SSL Connection Error

### ISSUE THREAD

**Issue by ductai202** [xpouyat/MK.IO#56]
When I try to connect MK client, I got this error 
![image](https://github.com/xpouyat/MK.IO/assets/70333438/ea03c650-46f6-4151-bd0c-686d905cbf46)
Do you know why

**Comment by xpouyat** [comment]
Hello,
I tested on my side and I don't have this issue.
Can you show the inner exception ?
Can you check that your MK.IO subscription is still active ? Also, check that you don't have a software that decrypts https in the middle (like Fiddler).

**Comment by ductai202** [comment]
![image](https://github.com/xpouyat/MK.IO/assets/70333438/d2a7a560-9115-45e7-9ddb-f1b27b5a6605)
Yes, my MK.IO subscription is still active. And when I try to check with fiddler it will show this. So how can I turn off that decrypts https ?

**Comment by ductai202** [comment]
![image](https://github.com/xpouyat/MK.IO/assets/70333438/933ef1b7-651f-4158-ba3f-df05478b4769)

**Comment by xpouyat** [comment]
Hello @ductai202 
Can you try the latest release v1.6.0 of the SDK? The endpoint URL has been changed to https://api.mk.io, as recommended by MediaKind.
https://www.nuget.org/packages/MK.IO/1.6.0
If it does not solve your issue, you should open a ticket with MediaKind.

**Comment by ductai202** [comment]
Hi @xpouyat , the root cause is from the firewall policy of my company. I resolved that, thank you for supporting me 😂
