### ISSUE TITLE
Migrate From `NewtonSoft.Json` to `System.Text.Json`

### ISSUE THREAD

**Issue by epicstar** [xpouyat/MK.IO#57]
I was wondering what you think of using .NET's standard JSON (de)serializer, `System.Text.Json`, instead of `NewtonSoft.Json`?

This isn't too much of a big deal. However, the library could reduce the number of dependencies and possible security issues from it

Here's docs from Microsoft to migrate: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-8-0

**Comment by xpouyat** [comment]
Hello Jeremy,
Thanks for the feedback !
I will look to it.

**Comment by xpouyat** [comment]
I did the migration to System.Text.Json. Actually, it was a big deal because of the number of changes.
It compiles now, but I still need to manage the polymorph deserialization with System.Text.Json (if possible), and it needs testing with real operations.
I published the new code to branch https://github.com/xpouyat/MK.IO/tree/dev-json
Please look to the code and test it if you have time.

**Comment by epicstar** [comment]
Definitely will try to test it. Is there a way to publish this code into nuget?

Please feel free to create a Draft PR or a normal PR if you feel it's ready to be merged in and you just need extra eyes.

**Comment by xpouyat** [comment]
Hum, I am hitting this issue: https://github.com/dotnet/runtime/issues/72604
Polymorphism in System.Text.Json needs the deterministic attribute, in our case "@odata.type", to be in first order, which is not the case with MK.IO json data.

**Comment by epicstar** [comment]
... That's unfortunate.... I guess we might have to table this until .NET 9.0,0?

**Comment by xpouyat** [comment]
Correct. I am testing polymorphism with .Net 9 preview. MK.IO Sdk should also work for .Net Core and .Net Framework but there is a dedicated System.Text.JSON lib in preview for these versions too.

**Comment by xpouyat** [comment]
Hey, after some work, code looks to work with .Net 9 preview and System.Text.Json.
I was able to make the code working with polymorphism.

**Comment by xpouyat** [comment]
I migrated SDK code to a new repo. The .NET 9 preview branch is now https://github.com/microsoft/MK.IO/tree/dotnet-9-with-native-json

**Comment by epicstar** [comment]
Awesome. Thank you!!!

**Comment by xpouyat** [comment]
Issue transferred to new repo.
