### ISSUE TITLE
Job Name is limited to 250 characters, not 63

### ISSUE THREAD

**Issue by dbakuntsev** [xpouyat/MK.IO#59]
This assertion is wrong:

https://github.com/xpouyat/MK.IO/blob/77a16e5118ec2f6a274dd9e9c4ef0af56ae91861/MK.IO/Job/JobsOperations.cs#L189C1-L189C76

Below is an actual response from the API that describes the limit, and it is consistent with Azure Media Services API.

```json
{
  "error": {
    "code": "1000.2000.5500.1020",
    "detail": "Job Validation failed. Field name:'A123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789' is invalid: ['Length must be between 1 and 260.']"
  },
  "ref": "9bb8f482-cba1-4204-a61d-fcc5545ad4df",
  "status": 400
}
```

**Comment by xpouyat** [comment]
Hello, this is based on some real tests. I found that 63 was the limit.

**Comment by dbakuntsev** [comment]
No longer accurate. A job with a name exactly 250 characters long is possible to submit now.

**Comment by dbakuntsev** [comment]
> No longer accurate. A job with a name exactly 250 characters long is possible to submit now.

For posterity, the job with 250 character long name was stuck at 0% progress for more than 20 minutes. So, it would seem that the MK.IO API has been fixed, but the implementation is till lacking. I'll have to submit a bug report with MK.IO, then.

**Comment by xpouyat** [comment]
Yes, this is what I found from my tests and the report from another user : https://github.com/xpouyat/MK.IO/issues/45

**Comment by dbakuntsev** [comment]
I've reached out to MK.IO and here's the reply:

> Hello,
> 
> Thank you for your email.
> 
> Yes we are aware of this and we opened a ticket with our dev team.
> 
> Just FYI the current limit of characters in the job name is 64, any job name with 65 characters or more will be in that state.
> We should have a fix for this within the next month or so.
> 
> Please, let us know if you have any other question.
> 
> Thank you!
> Sergio Lafuente.

I suppose this issue should be revisited after MK.IO addresses the problem on their end.

**Comment by xpouyat** [comment]
Yes, let's monitor this issue and will change the limit in the SDK when the MK.IO platform does not have this issue anymore.
